/* eslint-disable */
'use strict'

const fs = require('fs')
const os = require('os')
const path = require('path')

const BRICK_ID = 'com.example.render-gallery'
let buffer = ''
let nextHostCallId = 1
const hostWaiters = new Map()

function send(message) {
  process.stdout.write(JSON.stringify(message) + '\n')
}

function sendHostCall(type, payload) {
  const id = `host_${nextHostCallId++}`
  send({ type, id, ...payload })
  return new Promise((resolve, reject) => {
    const timer = setTimeout(() => {
      hostWaiters.delete(id)
      reject(new Error(`Host call timed out: ${type}`))
    }, 10_000)
    hostWaiters.set(id, { resolve, reject, timer })
  })
}

function handleHostResult(message) {
  if (message.type !== 'host.result' && message.type !== 'host.error') return false
  const waiter = hostWaiters.get(message.id)
  if (!waiter) return true
  clearTimeout(waiter.timer)
  hostWaiters.delete(message.id)
  if (message.type === 'host.error') {
    const err = new Error(message.error?.message || 'Host call failed')
    err.code = message.error?.code
    waiter.reject(err)
  } else {
    waiter.resolve(message.result)
  }
  return true
}

function ensureDir() {
  const dir = path.join(os.tmpdir(), 'brickly-render-gallery')
  fs.mkdirSync(dir, { recursive: true })
  return dir
}

function writeTextFile(dir, title) {
  const filePath = path.join(dir, 'render-gallery-report.md')
  fs.writeFileSync(
    filePath,
    `# ${title}\n\nThis file is generated by ${BRICK_ID}.\n\n- It should render as a file card.\n- Opening/downloading should use the file path.\n`,
    'utf8'
  )
  return filePath
}

function svgString(title) {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="720" height="420" viewBox="0 0 720 420">
  <rect width="720" height="420" rx="28" fill="#f8fafc"/>
  <rect x="44" y="44" width="632" height="332" rx="24" fill="#eef2ff" stroke="#4f46e5" stroke-width="4"/>
  <circle cx="130" cy="130" r="44" fill="#facc15"/>
  <path d="M84 330 244 180l104 96 68-72 220 126Z" fill="#0f766e"/>
  <text x="64" y="82" font-family="system-ui, sans-serif" font-size="28" font-weight="700" fill="#312e81">${escapeXml(title)}</text>
  <text x="64" y="372" font-family="ui-monospace, monospace" font-size="18" fill="#475569">image/file/resource renderer demo</text>
</svg>`
}

function svgDataUrl(title) {
  return `data:image/svg+xml;base64,${Buffer.from(svgString(title), 'utf8').toString('base64')}`
}

function writeSvgFile(dir, title) {
  const filePath = path.join(dir, 'render-gallery-image.svg')
  fs.writeFileSync(filePath, svgString(title), 'utf8')
  return filePath
}

function writeWavFile(dir) {
  const filePath = path.join(dir, 'render-gallery-tone.wav')
  const sampleRate = 8000
  const seconds = 1
  const samples = sampleRate * seconds
  const dataSize = samples * 2
  const buffer = Buffer.alloc(44 + dataSize)
  buffer.write('RIFF', 0)
  buffer.writeUInt32LE(36 + dataSize, 4)
  buffer.write('WAVE', 8)
  buffer.write('fmt ', 12)
  buffer.writeUInt32LE(16, 16)
  buffer.writeUInt16LE(1, 20)
  buffer.writeUInt16LE(1, 22)
  buffer.writeUInt32LE(sampleRate, 24)
  buffer.writeUInt32LE(sampleRate * 2, 28)
  buffer.writeUInt16LE(2, 32)
  buffer.writeUInt16LE(16, 34)
  buffer.write('data', 36)
  buffer.writeUInt32LE(dataSize, 40)
  for (let i = 0; i < samples; i += 1) {
    const t = i / sampleRate
    const value = Math.round(Math.sin(2 * Math.PI * 440 * t) * 0.25 * 32767)
    buffer.writeInt16LE(value, 44 + i * 2)
  }
  fs.writeFileSync(filePath, buffer)
  return filePath
}

function writeVideoPlaceholder(dir) {
  const filePath = path.join(dir, 'render-gallery-video-placeholder.svg')
  fs.writeFileSync(
    filePath,
    `<svg xmlns="http://www.w3.org/2000/svg" width="640" height="360" viewBox="0 0 640 360">
  <rect width="640" height="360" rx="24" fill="#111827"/>
  <polygon points="276,116 276,244 396,180" fill="#f8fafc"/>
  <text x="32" y="328" font-family="system-ui, sans-serif" font-size="22" fill="#cbd5e1">Video card fallback placeholder</text>
</svg>`,
    'utf8'
  )
  return filePath
}

async function registerResource(filePath, mimeType, name) {
  return sendHostCall('host.resource.register', {
    resource: {
      filePath,
      mimeType,
      name,
      size: fs.statSync(filePath).size,
      ttlMs: 30 * 60_000
    }
  })
}

async function showAll(id, input) {
  const title = String((input && input.title) || 'Brickly Render Gallery')
  const dir = ensureDir()
  const textFile = writeTextFile(dir, title)
  const svgFile = writeSvgFile(dir, title)
  const wavFile = writeWavFile(dir)
  const videoPlaceholder = writeVideoPlaceholder(dir)
  const resource = await registerResource(svgFile, 'image/svg+xml', 'registered-render-gallery-image.svg')

  const outputs = {
    markdown: `# ${title}

This command emits a broad set of renderer fixtures.

- [x] Markdown with **GFM**
- [x] Tables and task lists
- [x] File/media/resource cards
- [ ] Mermaid and LaTeX are intentionally not enabled yet

| Renderer | Expected UI |
| --- | --- |
| image | inline preview |
| file | metadata card |
| resource | reference card |

> Dangerous HTML should stay inert: <script>alert("nope")</script>

## Inline styles

Use \`inline code\`, **bold text**, *italic text*, ~~strikethrough~~, and a [safe link](https://example.com).

1. First ordered item
2. Second ordered item
   - Nested unordered item
   - Another nested item

---

## JavaScript code block

\`\`\`javascript
const renderers = ['markdown', 'code', 'image', 'file']

function describe(name) {
  return {
    name,
    ready: true,
    generatedAt: new Date().toISOString()
  }
}

console.table(renderers.map(describe))
\`\`\`

## Python code block

\`\`\`python
from dataclasses import dataclass

@dataclass
class Renderer:
    name: str
    ready: bool = True

print(Renderer("markdown"))
\`\`\`

## SQL code block

\`\`\`sql
select renderer, format, status
from brickly_outputs
where status = 'ready'
order by renderer;
\`\`\``,
    text: [
      '2026-05-16T10:00:00 INFO render gallery started',
      '2026-05-16T10:00:01 WARN this should stay plain text',
      '2026-05-16T10:00:02 ERROR simulated log line',
      'No Markdown should be inferred here even with # and - characters.'
    ].join('\n'),
    code: `import { readFile } from 'node:fs/promises'

export async function summarizePackageJson(filePath) {
  const raw = await readFile(filePath, 'utf8')
  const pkg = JSON.parse(raw)
  return {
    name: pkg.name ?? 'unknown',
    dependencies: Object.keys(pkg.dependencies ?? {}),
    private: Boolean(pkg.private)
  }
}

summarizePackageJson('./package.json')
  .then(console.log)
  .catch((error) => {
    console.error('Failed to summarize package.json', error)
    process.exitCode = 1
  })`,
    json: {
      brickId: BRICK_ID,
      generatedAt: new Date().toISOString(),
      nested: { markdown: true, artifacts: true }
    },
    table: [
      { renderer: 'markdown', format: 'markdown', status: 'ready' },
      { renderer: 'image', format: 'image', status: 'ready' },
      { renderer: 'file', format: 'file', status: 'ready' },
      { renderer: 'resource', format: 'resource', status: 'metadata only' }
    ],
    imageDataUrl: svgDataUrl(title),
    imageFile: {
      kind: 'image',
      filePath: svgFile,
      mimeType: 'image/svg+xml',
      name: path.basename(svgFile),
      size: fs.statSync(svgFile).size
    },
    file: {
      kind: 'file',
      filePath: textFile,
      mimeType: 'text/markdown',
      name: path.basename(textFile),
      size: fs.statSync(textFile).size
    },
    audio: {
      kind: 'audio',
      filePath: wavFile,
      mimeType: 'audio/wav',
      name: path.basename(wavFile),
      size: fs.statSync(wavFile).size
    },
    video: {
      kind: 'video',
      filePath: videoPlaceholder,
      mimeType: 'image/svg+xml',
      name: path.basename(videoPlaceholder),
      size: fs.statSync(videoPlaceholder).size
    },
    resource: {
      kind: 'resource',
      resourceId: resource.resourceId,
      mimeType: resource.mimeType,
      name: resource.name,
      size: resource.size,
      filePath: resource.filePath,
      expiresAt: resource.expiresAt
    }
  }

  let index = 0
  const entries = Object.entries(outputs)
  for (const [name, value] of entries) {
    send({ type: 'command.progress', id, progress: index / entries.length, message: `output ${name}` })
    send({ type: 'command.output', id, name, value })
    index += 1
  }
  send({ type: 'command.progress', id, progress: 1, message: 'done' })
  send({ type: 'command.result', id, result: { ok: true, outputs: entries.length, tempDir: dir } })
}

async function singleImage(id) {
  send({ type: 'command.result', id, result: svgDataUrl('Single Image Output') })
}

async function handleInvoke(message) {
  const { id, commandId, input } = message
  try {
    if (commandId === 'show-all') await showAll(id, input)
    else if (commandId === 'single-image') await singleImage(id)
    else {
      send({
        type: 'command.error',
        id,
        error: { code: 'COMMAND_NOT_FOUND', message: `Unknown command: ${commandId}` }
      })
    }
  } catch (error) {
    send({
      type: 'command.error',
      id,
      error: {
        code: error.code || 'INTERNAL_ERROR',
        message: error.message || String(error)
      }
    })
  } finally {
    send({ type: 'command.done', id })
  }
}

function handleMessage(message) {
  if (handleHostResult(message)) return
  if (message.type === 'host.hello') {
    send({ type: 'runtime.ready', protocolVersion: '0.1.0', brickId: BRICK_ID })
    return
  }
  if (message.type === 'command.invoke') {
    void handleInvoke(message)
    return
  }
  if (message.type === 'runtime.shutdown') {
    send({ type: 'runtime.bye' })
    process.exit(0)
  }
}

function escapeXml(value) {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

process.stdin.setEncoding('utf8')
process.stdin.on('data', (chunk) => {
  buffer += chunk
  let idx
  while ((idx = buffer.indexOf('\n')) >= 0) {
    const line = buffer.slice(0, idx).trim()
    buffer = buffer.slice(idx + 1)
    if (!line) continue
    try {
      handleMessage(JSON.parse(line))
    } catch (error) {
      process.stderr.write(`[render-gallery] invalid message: ${error.message}\n`)
    }
  }
})
