// 由 Brickly 生成：原 Wails 绑定的平台化替身。
// 导出名与原版一致（原版组件零改动），内部直接走 Brickly 命令（见 bridge.js）。
// 不再有 ByID 哈希、$Create 转换器与模型反序列化——Go 侧返回纯 JSON。
import { call as __call } from "./bridge.js";
export function AppCheckSunnyNet(){return __call("AppCheckSunnyNet",[])}
export function AppDeleteSession(tid){return __call("AppDeleteSession",[tid])}
export function AppDisconnectTCPRequest(id){return __call("AppDisconnectTCPRequest",[id])}
export function AppEncodingCall(obj){return __call("AppEncodingCall",[obj])}
export function AppEncryptCall(obj){return __call("AppEncryptCall",[obj])}
export function AppExport(list,savePath){return __call("AppExport",[list,savePath])}
export function AppGenerateCode(Theology,Language,Module){return __call("AppGenerateCode",[Theology,Language,Module])}
export function AppGenerateCodeInterface(Theology){return __call("AppGenerateCodeInterface",[Theology])}
export function AppGetEditorFontSize(){return __call("AppGetEditorFontSize",[])}
export function AppGetGenerateCodeInterface(){return __call("AppGetGenerateCodeInterface",[])}
export function AppGetTheme(isDark){return __call("AppGetTheme",[isDark])}
export function AppImport(filePath){return __call("AppImport",[filePath])}
export function AppInsertDone(){return __call("AppInsertDone",[])}
export function AppIsSetPort(){return __call("AppIsSetPort",[])}
export function AppResendRequest(id,count,BreakMode){return __call("AppResendRequest",[id,count,BreakMode])}
export function AppSaveGenerateCodeInterface(code){return __call("AppSaveGenerateCodeInterface",[code])}
export function AppSaveRequestImg(Theology,ImgType,IsRequest,path){return __call("AppSaveRequestImg",[Theology,ImgType,IsRequest,path])}
export function AppSetEditorFontSize(size){return __call("AppSetEditorFontSize",[size])}
export function AppStartInsert(){return __call("AppStartInsert",[])}
export function AppStartSelectRequest(isSelect){return __call("AppStartSelectRequest",[isSelect])}
export function AppVersion(){return __call("AppVersion",[])}
export function ApplyHTTPSProtocol(sendIsHTTP1,protoJSON,randomJa3){return __call("ApplyHTTPSProtocol",[sendIsHTTP1,protoJSON,randomJa3])}
export function AuthModeCreate(){return __call("AuthModeCreate",[])}
export function AuthModeList(){return __call("AuthModeList",[])}
export function AuthModeRemove(id){return __call("AuthModeRemove",[id])}
export function AuthModeSet(id,User,Pass){return __call("AuthModeSet",[id,User,Pass])}
export function AuthenticationList(){return __call("AuthenticationList",[])}
export function AuthenticationRemove(id){return __call("AuthenticationRemove",[id])}
export function AuthenticationUpdate(id,User,Pass){return __call("AuthenticationUpdate",[id,User,Pass])}
export function CallKeys(id){return __call("CallKeys",[id])}
export function CallTools(name,open,args){return __call("CallTools",[name,open,args])}
export function CancelIEProxy(){return __call("CancelIEProxy",[])}
export function ClearAllSession(){return __call("ClearAllSession",[])}
export function ClearAllSessionMessageIdArray(theology){return __call("ClearAllSessionMessageIdArray",[theology])}
export function ClipboardReadAll(){return __call("ClipboardReadAll",[])}
export function ClipboardWriteAll(value){return __call("ClipboardWriteAll",[value])}
export function CopySessionMessageIdArray(theology,CopyType,MessageIdArray){return __call("CopySessionMessageIdArray",[theology,CopyType,MessageIdArray])}
export function CreateAuthentication(){return __call("CreateAuthentication",[])}
export function CreateProxyWay(){return __call("CreateProxyWay",[])}
export function CreateReplaceBody(){return __call("CreateReplaceBody",[])}
export function CreateReplaceHost(){return __call("CreateReplaceHost",[])}
export function CreateRequestCert(){return __call("CreateRequestCert",[])}
export function CustomToolsAdd(filePath){return __call("CustomToolsAdd",[filePath])}
export function CustomToolsDel(id){return __call("CustomToolsDel",[id])}
export function CustomToolsList(){return __call("CustomToolsList",[])}
export function DefaultColor(IsDark){return __call("DefaultColor",[IsDark])}
export function DelSessionMessageIdArray(theology,MessageIdArray){return __call("DelSessionMessageIdArray",[theology,MessageIdArray])}
export function DoHTTPGenerateCode(req){return __call("DoHTTPGenerateCode",[req])}
export function DoHTTPRequest(req){return __call("DoHTTPRequest",[req])}
export function ExecCustomTools(id){return __call("ExecCustomTools",[id])}
export function ExportCert(path){return __call("ExportCert",[path])}
export function FindSession(info){return __call("FindSession",[info])}
export function FreeAllRequest(){return __call("FreeAllRequest",[])}
export function GOOS(){return __call("GOOS",[])}
export function GetAgGridDarkTheme(){return __call("GetAgGridDarkTheme",[])}
export function GetAgGridLightTheme(){return __call("GetAgGridLightTheme",[])}
export function GetAllProcessesList(){return __call("GetAllProcessesList",[])}
export function GetAllStream(Theology){return __call("GetAllStream",[Theology])}
export function GetBaseSettingsValue(){return __call("GetBaseSettingsValue",[])}
export function GetColumnState(){return __call("GetColumnState",[])}
export function GetError(){return __call("GetError",[])}
export function GetHTTPRequestBody(Theology,getAllBody){return __call("GetHTTPRequestBody",[Theology,getAllBody])}
export function GetHTTPResponseBody(Theology,getAllBody){return __call("GetHTTPResponseBody",[Theology,getAllBody])}
export function GetHTTPSProto(){return __call("GetHTTPSProto",[])}
export function GetHTTPSession(Theology){return __call("GetHTTPSession",[Theology])}
export function GetHomeTextMark(){return __call("GetHomeTextMark",[])}
export function GetIPV4InterfaceAdders(){return __call("GetIPV4InterfaceAdders",[])}
export function GetInterfaceOutRouterAdders(){return __call("GetInterfaceOutRouterAdders",[])}
export function GetKeys(){return __call("GetKeys",[])}
export function GetListColor(IsDark){return __call("GetListColor",[IsDark])}
export function GetLocalServerPATH(){return __call("GetLocalServerPATH",[])}
export function GetMustTcpRoles(){return __call("GetMustTcpRoles",[])}
export function GetMustTcpType(){return __call("GetMustTcpType",[])}
export function GetPort(){return __call("GetPort",[])}
export function GetProxyDns(){return __call("GetProxyDns",[])}
export function GetProxyRoles(){return __call("GetProxyRoles",[])}
export function GetRandomJa3(){return __call("GetRandomJa3",[])}
export function GetSendIsHTTP1(){return __call("GetSendIsHTTP1",[])}
export function GetSessionMessageBody(Theology,MessageId){return __call("GetSessionMessageBody",[Theology,MessageId])}
export function GetSocketFilter(theology){return __call("GetSocketFilter",[theology])}
export function GetTour(newTour){return __call("GetTour",[newTour])}
export function GoGetHex(data){return __call("GoGetHex",[data])}
export function IsDark(){return __call("IsDark",[])}
export function IsGetSelectRequest(){return __call("IsGetSelectRequest",[])}
export function IsLoadDevice(){return __call("IsLoadDevice",[])}
export function ListSearch(FilterJson){return __call("ListSearch",[FilterJson])}
export function LoadDevice(mode){return __call("LoadDevice",[mode])}
export function MCPDisable(){return __call("MCPDisable",[])}
export function MCPEnable(port){return __call("MCPEnable",[port])}
export function MCPListOpsJSON(){return __call("MCPListOpsJSON",[])}
export function MCPStatusJSON(){return __call("MCPStatusJSON",[])}
export function McpFuncRes(res){return __call("McpFuncRes",[res])}
export function OpenSunnyFile(prompt){return __call("OpenSunnyFile",[prompt])}
export function PrintScriptLog($0,...info){return __call("PrintScriptLog",[$0,...info])}
export function ProcessAddName(name){return __call("ProcessAddName",[name])}
export function ProcessAddPid(pid){return __call("ProcessAddPid",[pid])}
export function ProcessAny(open,StopNetwork){return __call("ProcessAny",[open,StopNetwork])}
export function ProcessDelName(name){return __call("ProcessDelName",[name])}
export function ProcessDelPid(pid){return __call("ProcessDelPid",[pid])}
export function ProtobufToJson(aa,skip){return __call("ProtobufToJson",[aa,skip])}
export function ProxyWayList(){return __call("ProxyWayList",[])}
export function ProxyWayRemove(id){return __call("ProxyWayRemove",[id])}
export function ProxyWayUpdate(id,URL,State,Note){return __call("ProxyWayUpdate",[id,URL,State,Note])}
export function ReapplyEngineFromConfig(){return __call("ReapplyEngineFromConfig",[])}
export function ReplaceBodyList(){return __call("ReplaceBodyList",[])}
export function ReplaceBodyRemove(id){return __call("ReplaceBodyRemove",[id])}
export function ReplaceBodyUpdate(id,Type,Source,Lod,New,Note,state){return __call("ReplaceBodyUpdate",[id,Type,Source,Lod,New,Note,state])}
export function ReplaceHostList(){return __call("ReplaceHostList",[])}
export function ReplaceHostRemove(id){return __call("ReplaceHostRemove",[id])}
export function ReplaceHostUpdate(id,Lod,New,Note){return __call("ReplaceHostUpdate",[id,Lod,New,Note])}
export function RequestCertGetCommonName(id){return __call("RequestCertGetCommonName",[id])}
export function RequestCertRemove(id){return __call("RequestCertRemove",[id])}
export function RequestCertSetFile(id,role,DoMain,file,pass,note){return __call("RequestCertSetFile",[id,role,DoMain,file,pass,note])}
export function RequestList(){return __call("RequestList",[])}
export function ResetALLConfig(){return __call("ResetALLConfig",[])}
export function SaveCustomTools(objInfo){return __call("SaveCustomTools",[objInfo])}
export function SaveScriptCode($0,code){return __call("SaveScriptCode",[$0,code])}
export function SaveSunnyFile(prompt){return __call("SaveSunnyFile",[prompt])}
export function ScriptLogInit(){return __call("ScriptLogInit",[])}
export function SessionActiveSend(Theology,isSendServer,SendType,wsType,_bs){return __call("SessionActiveSend",[Theology,isSendServer,SendType,wsType,_bs])}
export function SetAuthMode(open){return __call("SetAuthMode",[open])}
export function SetBreakMode(working){return __call("SetBreakMode",[working])}
export function SetColumnState(ColumnState){return __call("SetColumnState",[ColumnState])}
export function SetDeviceStopUpdate(stop){return __call("SetDeviceStopUpdate",[stop])}
export function SetDisableCache(Disable){return __call("SetDisableCache",[Disable])}
export function SetDisableTCP(Disable){return __call("SetDisableTCP",[Disable])}
export function SetDisableUDP(Disable){return __call("SetDisableUDP",[Disable])}
export function SetHTTPSProto(proto){return __call("SetHTTPSProto",[proto])}
export function SetHomeTextMark(TextMark){return __call("SetHomeTextMark",[TextMark])}
export function SetIEProxy(){return __call("SetIEProxy",[])}
export function SetInterfaceOutRouterAdders(ip){return __call("SetInterfaceOutRouterAdders",[ip])}
export function SetIsDark(IsDark){return __call("SetIsDark",[IsDark])}
export function SetIsEditKeyDown(i){return __call("SetIsEditKeyDown",[i])}
export function SetKeys(obj){return __call("SetKeys",[obj])}
export function SetLimitRequestSize(size){return __call("SetLimitRequestSize",[size])}
export function SetListColor(IsDark,ColorID,Color){return __call("SetListColor",[IsDark,ColorID,Color])}
export function SetMustTcpRoles(Type,Roles){return __call("SetMustTcpRoles",[Type,Roles])}
export function SetPort(Port,noStart){return __call("SetPort",[Port,noStart])}
export function SetProxyDns(dns){return __call("SetProxyDns",[dns])}
export function SetProxyRoles(roles){return __call("SetProxyRoles",[roles])}
export function SetRandomJa3(open){return __call("SetRandomJa3",[open])}
export function SetRequestNextBreakMode(Theology,working){return __call("SetRequestNextBreakMode",[Theology,working])}
export function SetSelectRequest(req){return __call("SetSelectRequest",[req])}
export function SetSendIsHTTP1(value){return __call("SetSendIsHTTP1",[value])}
export function SetWorking(working){return __call("SetWorking",[working])}
export function Start(){return __call("Start",[])}
export function StreamSearch(Theology,FilterJson){return __call("StreamSearch",[Theology,FilterJson])}
export function Theme(isDark,_type,Theme){return __call("Theme",[isDark,_type,Theme])}
export function URLQueryEscape(value){return __call("URLQueryEscape",[value])}
export function URLQueryUnescape(value){return __call("URLQueryUnescape",[value])}
export function UpdateHttpRequest(Theology,req){return __call("UpdateHttpRequest",[Theology,req])}
export function UpdateHttpResponse(Theology,req){return __call("UpdateHttpResponse",[Theology,req])}
export function UpdateNote(Theology,Note){return __call("UpdateNote",[Theology,Note])}
