'use strict'
const { BricklyRuntime } = require('@syllm/brickly-sdk')
const brick = new BricklyRuntime()
const proto = Object.getPrototypeOf(brick)
console.log('runtime.ui:', typeof brick.ui)
console.log('runtime.log.warn:', typeof brick.log?.warn)
console.log('runtime.invoke:', typeof brick.invoke)
console.log('runtime.onCommand:', typeof proto.onCommand)
const sdkPkg = require('@syllm/brickly-sdk/package.json')
console.log('sdk version:', sdkPkg.version)
const path = require('path')
const fs = require('fs')
const sdkRoot = path.dirname(require.resolve('@syllm/brickly-sdk/package.json'))
const dist = fs.readdirSync(path.join(sdkRoot, 'dist'), { recursive: true }).join(',')
console.log('has window handle:', dist.includes('handle'))
